apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: cincinnati
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: cincinnati
  displayName: cincinnati
  publisher: Red Hat
  authorizationToken:
    secretName: quay-registry-cincinnati
